//! Host-testable clipboard classification and pasteboard state decisions.

use glide_platform::{ClipboardFormat, ClipboardMarker, ClipboardSensitivity};
use std::path::PathBuf;
use std::time::Duration;

pub(crate) const MARKER_TYPE: &str = "org.glide.clipboard-marker";
pub(crate) const CONCEALED_TYPE: &str = "org.nspasteboard.ConcealedType";
pub(crate) const TRANSIENT_TYPE: &str = "org.nspasteboard.TransientType";
pub(crate) const AUTO_GENERATED_TYPE: &str = "org.nspasteboard.AutoGeneratedType";
pub(crate) const FILE_URL_TYPE: &str = "public.file-url";
pub(crate) const MAX_TIFF_PIXELS: u64 = 8 * 1024 * 1024;
pub(crate) const MAX_TIFF_DIMENSION: u32 = 16_384;
const MAX_TIFF_TAGS: usize = 4096;

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) enum NativeType {
    Text,
    Html,
    Rtf,
    Png,
    Tiff,
    Files,
    Marker,
    Concealed,
    Transient,
    AutoGenerated,
    Unsupported,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) enum ImageSource {
    Png,
    Tiff,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) enum PollDecision {
    Unchanged,
    OwnWrite,
    ExternalChange,
}

pub(crate) fn classify_type(uti: &str) -> NativeType {
    match uti {
        "public.utf8-plain-text" | "NSStringPboardType" => NativeType::Text,
        "public.html" | "NSHTMLPboardType" => NativeType::Html,
        "public.rtf" | "NSRTFPboardType" => NativeType::Rtf,
        "public.png" | "NSPasteboardTypePNG" => NativeType::Png,
        "public.tiff" | "NSTIFFPboardType" => NativeType::Tiff,
        FILE_URL_TYPE | "NSFilenamesPboardType" => NativeType::Files,
        MARKER_TYPE => NativeType::Marker,
        CONCEALED_TYPE => NativeType::Concealed,
        TRANSIENT_TYPE => NativeType::Transient,
        AUTO_GENERATED_TYPE => NativeType::AutoGenerated,
        _ => NativeType::Unsupported,
    }
}

pub(crate) fn sensitivity_for_types<'a>(
    types: impl IntoIterator<Item = &'a str>,
) -> ClipboardSensitivity {
    let mut result = ClipboardSensitivity::default();
    for ty in types {
        match classify_type(ty) {
            NativeType::Concealed => result.concealed = true,
            NativeType::Transient => result.transient = true,
            NativeType::AutoGenerated => result.auto_generated = true,
            _ => {}
        }
    }
    result
}

pub(crate) fn formats_for_types<'a>(
    types: impl IntoIterator<Item = &'a str>,
) -> Vec<ClipboardFormat> {
    let mut formats = Vec::with_capacity(5);
    let mut has_png = false;
    let mut has_tiff = false;
    for ty in types {
        let format = match classify_type(ty) {
            NativeType::Text => Some(ClipboardFormat::Text),
            NativeType::Html => Some(ClipboardFormat::Html),
            NativeType::Rtf => Some(ClipboardFormat::Rtf),
            NativeType::Png => {
                has_png = true;
                None
            }
            NativeType::Tiff => {
                has_tiff = true;
                None
            }
            NativeType::Files => Some(ClipboardFormat::Files),
            _ => None,
        };
        if let Some(format) = format {
            if !formats.contains(&format) {
                formats.push(format);
            }
        }
    }
    if choose_image_source(has_png, has_tiff).is_some() {
        formats.push(ClipboardFormat::Png);
    }
    formats
}

pub(crate) const fn choose_image_source(has_png: bool, has_tiff: bool) -> Option<ImageSource> {
    if has_png {
        Some(ImageSource::Png)
    } else if has_tiff {
        Some(ImageSource::Tiff)
    } else {
        None
    }
}

pub(crate) fn poll_decision(
    previous_count: isize,
    current_count: isize,
    completed_write_count: Option<isize>,
) -> PollDecision {
    if previous_count == current_count {
        PollDecision::Unchanged
    } else if completed_write_count == Some(current_count) {
        PollDecision::OwnWrite
    } else {
        PollDecision::ExternalChange
    }
}

pub(crate) fn next_poll_interval(
    current: Duration,
    changed: bool,
    minimum: Duration,
    maximum: Duration,
) -> Duration {
    if changed {
        return minimum;
    }
    let doubled = current.saturating_mul(2);
    if doubled < minimum {
        minimum
    } else if doubled > maximum {
        maximum
    } else {
        doubled
    }
}

pub(crate) fn owns_delayed_item(
    expected_count: isize,
    current_count: isize,
    observed_marker: Option<ClipboardMarker>,
    expected_marker: ClipboardMarker,
) -> bool {
    expected_count == current_count && observed_marker == Some(expected_marker)
}

pub(crate) fn encode_marker(marker: ClipboardMarker) -> [u8; 8] {
    marker.0.to_be_bytes()
}

pub(crate) fn decode_marker(bytes: &[u8]) -> Option<ClipboardMarker> {
    if bytes.len() != 8 {
        return None;
    }
    let raw: [u8; 8] = bytes.get(..8)?.try_into().ok()?;
    Some(ClipboardMarker(u64::from_be_bytes(raw)))
}

/// Validates a single-page classic TIFF's first image before handing it to the platform decoder.
/// BigTIFF, multi-page TIFF, malformed headers, and excessive decoded samples fail closed.
pub(crate) fn safe_tiff_dimensions(data: &[u8]) -> Option<(u32, u32)> {
    let little_endian = match data.get(..2)? {
        b"II" => true,
        b"MM" => false,
        _ => return None,
    };
    if read_u16(data, 2, little_endian)? != 42 {
        return None;
    }
    let ifd_offset = usize::try_from(read_u32(data, 4, little_endian)?).ok()?;
    let entry_count = usize::from(read_u16(data, ifd_offset, little_endian)?);
    if entry_count > MAX_TIFF_TAGS {
        return None;
    }
    let entries_start = ifd_offset.checked_add(2)?;
    let entries_bytes = entry_count.checked_mul(12)?;
    let entries_end = entries_start.checked_add(entries_bytes)?;
    let next_ifd = read_u32(data, entries_end, little_endian)?;
    if next_ifd != 0 {
        return None;
    }

    let mut width = None;
    let mut height = None;
    let mut samples_per_pixel = None;
    let mut bits_per_sample = None;
    let mut max_bits = 1u32;
    for index in 0..entry_count {
        let entry = entries_start.checked_add(index.checked_mul(12)?)?;
        let tag = read_u16(data, entry, little_endian)?;
        if tag != 256 && tag != 257 && tag != 258 && tag != 277 {
            continue;
        }
        let field_type = read_u16(data, entry.checked_add(2)?, little_endian)?;
        let count = read_u32(data, entry.checked_add(4)?, little_endian)?;
        let value_offset = entry.checked_add(8)?;
        match tag {
            256 | 257 => {
                if count != 1 || (tag == 256 && width.is_some()) || (tag == 257 && height.is_some())
                {
                    return None;
                }
                let value = match field_type {
                    3 => u32::from(read_u16(data, value_offset, little_endian)?),
                    4 => read_u32(data, value_offset, little_endian)?,
                    _ => return None,
                };
                if tag == 256 {
                    width = Some(value);
                } else {
                    height = Some(value);
                }
            }
            258 => {
                if field_type != 3 || !(1..=4).contains(&count) || bits_per_sample.is_some() {
                    return None;
                }
                let short_count = usize::try_from(count).ok()?;
                let values_offset = if short_count <= 2 {
                    value_offset
                } else {
                    usize::try_from(read_u32(data, value_offset, little_endian)?).ok()?
                };
                for sample_index in 0..short_count {
                    let offset = values_offset.checked_add(sample_index.checked_mul(2)?)?;
                    let bits = read_u16(data, offset, little_endian)?;
                    if bits == 0 || bits > 16 {
                        return None;
                    }
                    max_bits = max_bits.max(u32::from(bits));
                }
                bits_per_sample = Some(count);
            }
            277 => {
                if field_type != 3 || count != 1 || samples_per_pixel.is_some() {
                    return None;
                }
                samples_per_pixel = Some(u32::from(read_u16(data, value_offset, little_endian)?));
            }
            _ => {}
        }
    }
    let width = width?;
    let height = height?;
    let samples_per_pixel = samples_per_pixel.unwrap_or(1);
    if !(1..=4).contains(&samples_per_pixel)
        || bits_per_sample.is_some_and(|count| count != samples_per_pixel)
    {
        return None;
    }
    if width == 0
        || height == 0
        || width > MAX_TIFF_DIMENSION
        || height > MAX_TIFF_DIMENSION
        || u64::from(width).checked_mul(u64::from(height))? > MAX_TIFF_PIXELS
        || u64::from(width)
            .checked_mul(u64::from(height))?
            .checked_mul(u64::from(samples_per_pixel))?
            .checked_mul(u64::from(max_bits))?
            > 64 * 1024 * 1024 * 8
    {
        return None;
    }
    Some((width, height))
}

fn read_u16(data: &[u8], offset: usize, little_endian: bool) -> Option<u16> {
    let raw: [u8; 2] = data.get(offset..offset.checked_add(2)?)?.try_into().ok()?;
    Some(if little_endian {
        u16::from_le_bytes(raw)
    } else {
        u16::from_be_bytes(raw)
    })
}

fn read_u32(data: &[u8], offset: usize, little_endian: bool) -> Option<u32> {
    let raw: [u8; 4] = data.get(offset..offset.checked_add(4)?)?.try_into().ok()?;
    Some(if little_endian {
        u32::from_le_bytes(raw)
    } else {
        u32::from_be_bytes(raw)
    })
}

/// Accept only local absolute file URLs. Malformed escapes, remote authorities, query/fragment
/// delimiters, NULs, non-UTF-8 paths, and parent traversal are rejected.
pub(crate) fn file_url_to_path(url: &str) -> Option<PathBuf> {
    let remainder = url.strip_prefix("file://")?;
    if remainder.contains(['?', '#']) {
        return None;
    }
    let path = if remainder.starts_with('/') {
        remainder
    } else {
        let (host, path) = remainder.split_once('/')?;
        if !host.eq_ignore_ascii_case("localhost") {
            return None;
        }
        return decode_absolute_path(&format!("/{path}"));
    };
    decode_absolute_path(path)
}

fn decode_absolute_path(encoded: &str) -> Option<PathBuf> {
    let bytes = encoded.as_bytes();
    let mut decoded = Vec::with_capacity(bytes.len());
    let mut index = 0;
    while index < bytes.len() {
        if bytes[index] == b'%' {
            let high = hex_value(*bytes.get(index + 1)?)?;
            let low = hex_value(*bytes.get(index + 2)?)?;
            decoded.push((high << 4) | low);
            index += 3;
        } else {
            decoded.push(bytes[index]);
            index += 1;
        }
    }
    if decoded.contains(&0) {
        return None;
    }
    let decoded = String::from_utf8(decoded).ok()?;
    if !decoded.starts_with('/')
        || decoded.starts_with("//")
        || decoded.split('/').any(|part| part == "..")
    {
        return None;
    }
    // File URLs always encode POSIX paths. Keep that representation portable in host tests,
    // where Windows PathBuf cannot report a drive-less POSIX path as absolute.
    Some(PathBuf::from(decoded))
}

const fn hex_value(byte: u8) -> Option<u8> {
    match byte {
        b'0'..=b'9' => Some(byte - b'0'),
        b'a'..=b'f' => Some(byte - b'a' + 10),
        b'A'..=b'F' => Some(byte - b'A' + 10),
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn classifies_formats_and_sensitive_types() {
        let types = [
            "public.utf8-plain-text",
            "public.html",
            "public.rtf",
            "public.tiff",
            FILE_URL_TYPE,
            CONCEALED_TYPE,
            TRANSIENT_TYPE,
        ];
        assert_eq!(
            formats_for_types(types),
            vec![
                ClipboardFormat::Text,
                ClipboardFormat::Html,
                ClipboardFormat::Rtf,
                ClipboardFormat::Files,
                ClipboardFormat::Png,
            ]
        );
        let sensitivity = sensitivity_for_types(types);
        assert!(sensitivity.concealed);
        assert!(sensitivity.transient);
        assert!(sensitivity.should_exclude());

        for (png, tiff, expected) in [
            (true, true, Some(ImageSource::Png)),
            (false, true, Some(ImageSource::Tiff)),
            (false, false, None),
        ] {
            assert_eq!(choose_image_source(png, tiff), expected);
        }
    }

    #[test]
    fn distinguishes_own_changes_from_external_changes() {
        let marker = ClipboardMarker(0x0102_0304_0506_0708);
        assert_eq!(decode_marker(&encode_marker(marker)), Some(marker));
        assert_eq!(decode_marker(&[1, 2]), None);
        assert_eq!(poll_decision(4, 4, Some(9)), PollDecision::Unchanged);
        assert_eq!(poll_decision(4, 5, Some(5)), PollDecision::OwnWrite);
        assert_eq!(poll_decision(4, 5, None), PollDecision::ExternalChange);
        assert_eq!(poll_decision(4, 6, Some(5)), PollDecision::ExternalChange);
        assert!(owns_delayed_item(5, 5, Some(marker), marker));
        assert!(!owns_delayed_item(5, 6, Some(marker), marker));
        assert!(!owns_delayed_item(5, 5, Some(ClipboardMarker(1)), marker));
    }

    #[test]
    fn poll_interval_backs_off_and_resets_after_changes() {
        let minimum = Duration::from_millis(100);
        let maximum = Duration::from_secs(1);
        assert_eq!(
            next_poll_interval(minimum, false, minimum, maximum),
            Duration::from_millis(200)
        );
        assert_eq!(
            next_poll_interval(Duration::from_millis(800), false, minimum, maximum),
            maximum
        );
        assert_eq!(next_poll_interval(maximum, true, minimum, maximum), minimum);
    }

    #[test]
    fn accepts_only_safe_local_file_urls() {
        assert_eq!(
            file_url_to_path("file:///Users/example/My%20File.txt"),
            Some(PathBuf::from("/Users/example/My File.txt"))
        );
        assert_eq!(
            file_url_to_path("file://localhost/Users/example/a%23b"),
            Some(PathBuf::from("/Users/example/a#b"))
        );
        assert_eq!(file_url_to_path("file://server/share/file"), None);
        assert_eq!(file_url_to_path("file:///Users/../secret"), None);
        assert_eq!(file_url_to_path("file:////server/share"), None);
        assert_eq!(file_url_to_path("file:///tmp/%00name"), None);
        assert_eq!(file_url_to_path("file:///tmp/%GG"), None);
    }

    #[test]
    fn bounds_classic_tiff_dimensions_before_native_decode() {
        let little = tiff_fixture(true, 1024, 768);
        let big = tiff_fixture(false, 640, 480);
        assert_eq!(safe_tiff_dimensions(&little), Some((1024, 768)));
        assert_eq!(safe_tiff_dimensions(&big), Some((640, 480)));

        let oversized = tiff_fixture(true, 16_384, 16_384);
        assert_eq!(safe_tiff_dimensions(&oversized), None);
        assert_eq!(safe_tiff_dimensions(b"II+\0\x08\0\0\0"), None);
        assert_eq!(safe_tiff_dimensions(b"not a tiff"), None);
        let mut multipage = tiff_fixture(true, 320, 240);
        multipage[34..38].copy_from_slice(&8u32.to_le_bytes());
        assert_eq!(safe_tiff_dimensions(&multipage), None);
        let mut overflowing = b"II*\0\xff\xff\xff\xff".to_vec();
        overflowing.resize(32, 0);
        assert_eq!(safe_tiff_dimensions(&overflowing), None);
    }

    fn tiff_fixture(little_endian: bool, width: u16, height: u16) -> Vec<u8> {
        let mut bytes = Vec::from(if little_endian { b"II" } else { b"MM" });
        push_u16(&mut bytes, 42, little_endian);
        push_u32(&mut bytes, 8, little_endian);
        push_u16(&mut bytes, 2, little_endian);
        push_u16(&mut bytes, 256, little_endian);
        push_u16(&mut bytes, 3, little_endian);
        push_u32(&mut bytes, 1, little_endian);
        push_u16(&mut bytes, width, little_endian);
        push_u16(&mut bytes, 0, little_endian);
        push_u16(&mut bytes, 257, little_endian);
        push_u16(&mut bytes, 3, little_endian);
        push_u32(&mut bytes, 1, little_endian);
        push_u16(&mut bytes, height, little_endian);
        push_u16(&mut bytes, 0, little_endian);
        push_u32(&mut bytes, 0, little_endian);
        bytes
    }

    fn push_u16(bytes: &mut Vec<u8>, value: u16, little_endian: bool) {
        bytes.extend(if little_endian {
            value.to_le_bytes()
        } else {
            value.to_be_bytes()
        });
    }

    fn push_u32(bytes: &mut Vec<u8>, value: u32, little_endian: bool) {
        bytes.extend(if little_endian {
            value.to_le_bytes()
        } else {
            value.to_be_bytes()
        });
    }
}
